<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns1="http://soa.indonesiapower.co.id/schema/calcproniastatus"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbCalcStatus"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateStatusDb"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns1 ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns3="http://soa.indonesiapower.co.id/schema/fault"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/IPApplication/PNCalcStatus/dbCalcStatus"
                xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/IPApplication/PNCalcStatus/UpdateStatusDb">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/dbCalcStatus.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Pronia3CalcStatusCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbCalcStatus"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/dbCalcStatus.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ResponseCalcproniastatus"
                                       namespace="http://soa.indonesiapower.co.id/schema/calcproniastatus"/>
        <oracle-xsl-mapper:param name="Response"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/UpdateStatusDb.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Pronia3CalcStatusCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateStatusDb"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU FEB 16 11:47:38 ICT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="Response"/>
  <xsl:template match="/">
    <tns:Pronia3CalcStatusCollection>
      <tns:Pronia3CalcStatus>
        <tns:id>
          <xsl:value-of select="/ns0:Pronia3CalcStatusCollection/ns0:Pronia3CalcStatus/ns0:id"/>
        </tns:id>
        <tns:unit>
          <xsl:value-of select="/ns0:Pronia3CalcStatusCollection/ns0:Pronia3CalcStatus/ns0:unit"/>
        </tns:unit>
        <tns:calcPeriod>
          <xsl:value-of select="/ns0:Pronia3CalcStatusCollection/ns0:Pronia3CalcStatus/ns0:calcPeriod"/>
        </tns:calcPeriod>
        <tns:etlStartDate>
          <xsl:value-of select="/ns0:Pronia3CalcStatusCollection/ns0:Pronia3CalcStatus/ns0:etlStartDate"/>
        </tns:etlStartDate>
        <tns:soaMessages>
          <xsl:value-of select="$Response/ns1:ResponseCalcproniastatus/ns1:response/ns1:ErrorMessage"/>
        </tns:soaMessages>
      </tns:Pronia3CalcStatus>
    </tns:Pronia3CalcStatusCollection>
  </xsl:template>
</xsl:stylesheet>
