<wsdl:definitions
     name="dbPronia3StatusDetail"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/IPApplication/PNCalcStatusDetail/dbPronia3StatusDetail"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/IPApplication/PNCalcStatusDetail/dbPronia3StatusDetail"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbPronia3StatusDetail"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbPronia3StatusDetail_plt" >
    <plt:role name="dbPronia3StatusDetail_role" >
      <plt:portType name="tns:dbPronia3StatusDetail_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="dbPronia3StatusDetail_plt" >
    <plt:role name="dbPronia3StatusDetail_role" >
      <plt:portType name="tns:dbPronia3StatusDetail_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="dbPronia3StatusDetail_plt" >
    <plt:role name="dbPronia3StatusDetail_role" >
      <plt:portType name="tns:dbPronia3StatusDetail_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="dbPronia3StatusDetail_plt" >
    <plt:role name="dbPronia3StatusDetail_role" >
      <plt:portType name="tns:dbPronia3StatusDetail_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbPronia3StatusDetail" schemaLocation="../Schemas/dbPronia3StatusDetail_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Pronia3CalcStatusDetailCollection_msg">
        <wsdl:part name="Pronia3CalcStatusDetailCollection" element="top:Pronia3CalcStatusDetailCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbPronia3StatusDetail_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:Pronia3CalcStatusDetailCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
