<wsdl:definitions
     name="dbUpdateSuccess"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/IPApplication/PNCalcStatusDetail/dbUpdateSuccess"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/IPApplication/PNCalcStatusDetail/dbUpdateSuccess"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbUpdateSuccess"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbUpdateSuccess_plt" >
    <plt:role name="dbUpdateSuccess_role" >
      <plt:portType name="tns:dbUpdateSuccess_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbUpdateSuccess" schemaLocation="../Schemas/dbUpdateSuccess_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Pronia3CalcStatusDetailCollection_msg">
        <wsdl:part name="Pronia3CalcStatusDetailCollection" element="top:Pronia3CalcStatusDetailCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbUpdateSuccess_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:Pronia3CalcStatusDetailCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
